name: battery
description: Battery Indicator
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.15.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0


flutter:
  plugin:
    platforms:
      android:
        package: studio.novikov.battery
        pluginClass: BatteryPlugin
#      ios:
#        pluginClass: BatteryPlugin
